### PR TITLE
Adds a better optimized node image.

### PR DESCRIPTION
**Pull request by SamTV12345**
node latest includes a lot of bloat that is not really needed for a normal nodejs application.

### CODE REVIEW

**Comment by hwgilbert16** [comment]
Have you tested this locally beyond just building the image? Alpine has discrepancies in regard to the C compiler and other small changes that could potentially throw issues with some of our dependencies, along with the image not being tested as extensively as the main Node images.

**Comment by SamTV12345** [comment]
Sorry. Should have been a draft. I'll continue once I have more time. It is crashing on an existing installation. Somehow without any error. Could it be prisma?

**Comment by hwgilbert16** [comment]
> It is crashing on an existing installation.

With this new alpine image, or the existing one that is published?

**Comment by SamTV12345** [comment]
> > It is crashing on an existing installation.
> 
> With this new alpine image, or the existing one that is published?

The new one. I'll have to take a deeper dive why it is crashing. Normally NodeJS should be platform independent and I didn't saw any installation in your Dockerfile. But yeah. It definitely needs some testing.

**Comment by hwgilbert16** [comment]
Seems like it was something with the environment file validation that (unsure why) only failed when using the Alpine image. Give it another shot after pulling from `develop` again.

**Comment by SamTV12345** [comment]
I get this:

```
10 migrations found in prisma/migrations


No pending migrations to apply.
Configuration validation error: "HTTP_PORT" is required

> scholarsome@1.0.5 serve:node
> npm run migrate && node dist/apps/api/main.js


> scholarsome@1.0.5 migrate
> npx prisma migrate deploy

Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "scholarsome" at "mariadb:3306"

10 migrations found in prisma/migrations


No pending migrations to apply.
Configuration validation error: "HTTP_PORT" is required

> scholarsome@1.0.5 serve:node
> npm run migrate && node dist/apps/api/main.js


> scholarsome@1.0.5 migrate
> npx prisma migrate deploy

Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "scholarsome" at "mariadb:3306"

10 migrations found in prisma/migrations


No pending migrations to apply.
Configuration validation error: "HTTP_PORT" is required
```

**Comment by SamTV12345** [comment]
I had to add HTTP_PORT and set the HOST variable. But now it is working without a problem. BTW you can set variables also with

```
web:
  env_file:
    - .env
 ```

that way you don't have to write VARIABLE=$VARIABLE and can just keep the other more complicated variables like database url.

**Comment by hwgilbert16** [comment]
> you can set variables also with

Not sure why I didn't have that - could have sworn I was just passing the file.

If you add that I'll merge this, the Alpine image is certainly smaller.

**Comment by SamTV12345** [comment]
Done

**Pull request merged**
